/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/usuarios/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra el perfil del comerciante */
        post: operations["UsuariosController_registrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/usuarios/acceso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inicia sesión y emite el JWT de acceso */
        post: operations["UsuariosController_acceder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terceros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista los terceros pertenecientes al comerciante autenticado con paginación */
        get: operations["TercerosController_listar"];
        put?: never;
        /** Registra un nuevo tercero asociado al comerciante */
        post: operations["TercerosController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/terceros/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene el detalle de un tercero por ID */
        get: operations["TercerosController_buscarPorId"];
        put?: never;
        post?: never;
        /** Elimina un tercero si no tiene contratos vinculados */
        delete: operations["TercerosController_eliminar"];
        options?: never;
        head?: never;
        /** Actualiza los datos de un tercero */
        patch: operations["TercerosController_actualizar"];
        trace?: never;
    };
    "/api/v1/fincas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista las fincas pertenecientes a los terceros del comerciante con paginación */
        get: operations["FincasController_listar"];
        put?: never;
        /** Registra una nueva finca geolocalizada asociada a un tercero */
        post: operations["FincasController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/fincas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene el detalle de una finca por ID */
        get: operations["FincasController_buscarPorId"];
        put?: never;
        post?: never;
        /** Elimina una finca si no tiene contratos vinculados */
        delete: operations["FincasController_eliminar"];
        options?: never;
        head?: never;
        /** Actualiza los datos o coordenadas de una finca */
        patch: operations["FincasController_actualizar"];
        trace?: never;
    };
    "/api/v1/contratos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista los contratos pertenecientes al comerciante autenticado con paginación opcional
         * @description Retorna todos los contratos accesibles por el tenant en sesión activa.
         */
        get: operations["ContratosController_listar"];
        put?: never;
        /**
         * Apertura un nuevo contrato de participación (lote)
         * @description Registra un nuevo contrato vinculando un tercero, una finca y el par inmutable de porcentajes de participación. El estado se inicializa automáticamente en "activo". Invariante de negocio obligatoria: la suma de porcentaje_comerciante y porcentaje_tercero debe ser exactamente igual a 100%.
         */
        post: operations["ContratosController_crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contratos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtiene el detalle de un contrato por su ID
         * @description Consulta un contrato específico asegurando aislamiento tenant.
         */
        get: operations["ContratosController_buscarPorId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualiza campos informativos o estado de un contrato
         * @description Permite modificar datos mutables (raza, peso_promedio_actual, cantidad_actual, valor_kilo_referencia, estado, fecha_cierre). Los porcentajes de participación son inmutables y no se pueden alterar.
         */
        patch: operations["ContratosController_actualizar"];
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_verificar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CrearUsuarioDto: {
            /**
             * @description Nombre del comerciante
             * @example María Quintero
             */
            nombre: string;
            /**
             * @description Correo electrónico único del comerciante
             * @example maria@ejemplo.com
             */
            email: string;
            /**
             * @description Contraseña en texto plano (se almacena con hash bcrypt, nunca en claro)
             * @example Secreto123
             */
            password: string;
        };
        UsuarioRegistradoDto: {
            /**
             * @description Identificador único del comerciante
             * @example a3bb189e-8bf9-3888-9912-ace4e6543002
             */
            id: string;
            /**
             * @description Nombre del comerciante
             * @example María Quintero
             */
            nombre: string;
            /**
             * @description Correo electrónico del comerciante
             * @example maria@ejemplo.com
             */
            email: string;
        };
        RespuestaErrorValidacionDto: {
            /**
             * @description Indica si la operación fue exitosa (siempre false en respuestas de error)
             * @example false
             */
            exito: boolean;
            /**
             * @description Ruta URL donde ocurrió el error
             * @example /api/v1/recurso
             */
            ruta: string;
            /**
             * @description Marca de tiempo en formato ISO 8601 en que ocurrió el error
             * @example 2026-09-21T16:00:00.000Z
             */
            marcaTiempo: string;
            /**
             * @description Mensaje descriptivo del fallo de validación
             * @example Error de validación en la petición: Parámetros inválidos o incompletos
             */
            mensaje: string;
            /**
             * @description Lista detallada de restricciones de validación no cumplidas
             * @example [
             *       "Parámetros inválidos o incompletos"
             *     ]
             */
            errores?: string[];
            /**
             * @description Código de estado HTTP 400 (Bad Request)
             * @example 400
             */
            codigoEstado: number;
        };
        RespuestaErrorConflictoDto: {
            /**
             * @description Indica si la operación fue exitosa (siempre false en respuestas de error)
             * @example false
             */
            exito: boolean;
            /**
             * @description Ruta URL donde ocurrió el error
             * @example /api/v1/recurso
             */
            ruta: string;
            /**
             * @description Marca de tiempo en formato ISO 8601 en que ocurrió el error
             * @example 2026-09-21T16:00:00.000Z
             */
            marcaTiempo: string;
            /**
             * @description Mensaje descriptivo del conflicto de estado o integridad referencial
             * @example Conflicto con el estado actual del recurso
             */
            mensaje: string;
            /**
             * @description Detalle del conflicto presentado
             * @example [
             *       "El registro ya existe o posee dependencias activas vinculadas"
             *     ]
             */
            errores?: string[];
            /**
             * @description Código de estado HTTP 409 (Conflict)
             * @example 409
             */
            codigoEstado: number;
        };
        RespuestaErrorServidorDto: {
            /**
             * @description Indica si la operación fue exitosa (siempre false en respuestas de error)
             * @example false
             */
            exito: boolean;
            /**
             * @description Ruta URL donde ocurrió el error
             * @example /api/v1/recurso
             */
            ruta: string;
            /**
             * @description Marca de tiempo en formato ISO 8601 en que ocurrió el error
             * @example 2026-09-21T16:00:00.000Z
             */
            marcaTiempo: string;
            /**
             * @description Mensaje descriptivo de error interno no controlado
             * @example Error interno del servidor
             */
            mensaje: string;
            /**
             * @description Código de estado HTTP 500 (Internal Server Error)
             * @example 500
             */
            codigoEstado: number;
        };
        CredencialesAccesoDto: {
            /**
             * @description Correo electrónico del comerciante
             * @example maria@ejemplo.com
             */
            email: string;
            /**
             * @description Contraseña del comerciante
             * @example Secreto123
             */
            password: string;
        };
        AccesoRespuestaDto: {
            /**
             * @description JWT de acceso firmado con expiración (usar como Bearer)
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            tokenAcceso: string;
            /** @description Perfil mínimo del comerciante autenticado */
            usuario: components["schemas"]["UsuarioRegistradoDto"];
        };
        RespuestaErrorNoAutorizadoDto: {
            /**
             * @description Indica si la operación fue exitosa (siempre false en respuestas de error)
             * @example false
             */
            exito: boolean;
            /**
             * @description Ruta URL donde ocurrió el error
             * @example /api/v1/recurso
             */
            ruta: string;
            /**
             * @description Marca de tiempo en formato ISO 8601 en que ocurrió el error
             * @example 2026-09-21T16:00:00.000Z
             */
            marcaTiempo: string;
            /**
             * @description Mensaje descriptivo del fallo de autenticación
             * @example No autorizado: token JWT ausente o credenciales inválidas
             */
            mensaje: string;
            /**
             * @description Lista descriptiva del motivo de no autorización
             * @example [
             *       "Credenciales de acceso inválidas"
             *     ]
             */
            errores?: string[];
            /**
             * @description Código de estado HTTP 401 (Unauthorized)
             * @example 401
             */
            codigoEstado: number;
        };
        CrearTerceroDto: {
            /**
             * @description Nombre completo o razón social del tercero
             * @example Juan Pérez Ganadería S.A.S.
             */
            nombre: string;
            /**
             * @description Número de documento de identidad o NIT
             * @example 900123456-7
             */
            documento: string;
            /**
             * @description Información de contacto (teléfono, email, dirección)
             * @example +57 300 123 4567
             */
            contacto: string;
        };
        TerceroRespuestaDto: {
            /**
             * @description Identificador único UUID del tercero
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            id: string;
            /**
             * @description Identificador único UUID del comerciante propietario
             * @example b1ffcd88-8b0a-3ef7-aa5c-5aa8ac270a22
             */
            usuario_id: string;
            /**
             * @description Nombre completo o razón social del tercero
             * @example Juan Pérez Ganadería S.A.S.
             */
            nombre: string;
            /**
             * @description Número de documento de identidad o NIT
             * @example 900123456-7
             */
            documento: string;
            /**
             * @description Información de contacto
             * @example +57 300 123 4567
             */
            contacto: string;
        };
        PaginaTercerosDto: {
            /** @description Listado de elementos paginados */
            elementos: components["schemas"]["TerceroRespuestaDto"][];
            /**
             * @description Cantidad total de registros encontrados para el tenant
             * @example 45
             */
            total: number;
            /**
             * @description Límite de registros solicitado o aplicado por página
             * @example 20
             */
            limite: number;
            /**
             * @description Cantidad de registros omitidos desde el inicio
             * @example 0
             */
            offset: number;
        };
        RespuestaErrorNoEncontradoDto: {
            /**
             * @description Indica si la operación fue exitosa (siempre false en respuestas de error)
             * @example false
             */
            exito: boolean;
            /**
             * @description Ruta URL donde ocurrió el error
             * @example /api/v1/recurso
             */
            ruta: string;
            /**
             * @description Marca de tiempo en formato ISO 8601 en que ocurrió el error
             * @example 2026-09-21T16:00:00.000Z
             */
            marcaTiempo: string;
            /**
             * @description Mensaje descriptivo del recurso no encontrado
             * @example Recurso no encontrado
             */
            mensaje: string;
            /**
             * @description Detalle del recurso no encontrado
             * @example [
             *       "Recurso no encontrado"
             *     ]
             */
            errores?: string[];
            /**
             * @description Código de estado HTTP 404 (Not Found)
             * @example 404
             */
            codigoEstado: number;
        };
        ActualizarTerceroDto: {
            /**
             * @description Nombre completo o razón social del tercero
             * @example Juan Pérez Ganadería Renovada
             */
            nombre?: string;
            /**
             * @description Número de documento de identidad o NIT
             * @example 900123456-8
             */
            documento?: string;
            /**
             * @description Información de contacto actualizada
             * @example +57 311 987 6543
             */
            contacto?: string;
        };
        CrearFincaDto: {
            /**
             * @description Identificador UUID del tercero propietario de la finca
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            tercero_id: string;
            /**
             * @description Nombre de la finca
             * @example Hacienda La Esperanza
             */
            nombre: string;
            /**
             * @description Dirección o vereda de ubicación
             * @example Vereda El Porvenir, Km 14 Vía Montería
             */
            direccion: string;
            /**
             * @description Latitud geográfica (-90 a 90)
             * @example 8.754321
             */
            latitud: number;
            /**
             * @description Longitud geográfica (-180 a 180)
             * @example -75.881234
             */
            longitud: number;
        };
        FincaRespuestaDto: {
            /**
             * @description Identificador único UUID de la finca
             * @example c2eedd77-7a0c-4ff6-995d-4aa7ac160b33
             */
            id: string;
            /**
             * @description Identificador UUID del tercero propietario
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            tercero_id: string;
            /**
             * @description Nombre de la finca
             * @example Hacienda La Esperanza
             */
            nombre: string;
            /**
             * @description Dirección o vereda de ubicación
             * @example Vereda El Porvenir, Km 14 Vía Montería
             */
            direccion: string;
            /**
             * @description Latitud geográfica
             * @example 8.754321
             */
            latitud: number;
            /**
             * @description Longitud geográfica
             * @example -75.881234
             */
            longitud: number;
        };
        PaginaFincasDto: {
            /** @description Listado de elementos paginados */
            elementos: components["schemas"]["FincaRespuestaDto"][];
            /**
             * @description Cantidad total de registros encontrados para el tenant
             * @example 45
             */
            total: number;
            /**
             * @description Límite de registros solicitado o aplicado por página
             * @example 20
             */
            limite: number;
            /**
             * @description Cantidad de registros omitidos desde el inicio
             * @example 0
             */
            offset: number;
        };
        ActualizarFincaDto: {
            /**
             * @description Nombre de la finca
             * @example Hacienda La Gran Esperanza
             */
            nombre?: string;
            /**
             * @description Dirección o vereda
             * @example Vereda El Porvenir, Sector 2
             */
            direccion?: string;
            /**
             * @description Latitud geográfica (-90 a 90)
             * @example 8.765432
             */
            latitud?: number;
            /**
             * @description Longitud geográfica (-180 a 180)
             * @example -75.876543
             */
            longitud?: number;
        };
        CrearContratoDto: {
            /**
             * @description Identificador UUID del tercero socio en participación
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            tercero_id: string;
            /**
             * @description Identificador UUID de la finca donde pastará el lote
             * @example b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22
             */
            finca_id: string;
            /**
             * @description Fecha y hora de apertura del contrato en formato ISO 8601
             * @example 2026-09-21T10:00:00.000Z
             */
            fecha_apertura: string;
            /**
             * @description Porcentaje de participación del comerciante (entre 0 y 100)
             * @example 60
             */
            porcentaje_comerciante: number;
            /**
             * @description Porcentaje de participación del tercero (entre 0 y 100)
             * @example 40
             */
            porcentaje_tercero: number;
            /**
             * @description Raza o cruce del lote inicial (opcional)
             * @example Brahman Blanco
             */
            raza?: string;
            /**
             * @description Peso promedio actual inicial del lote en kg (opcional)
             * @example 350.5
             */
            peso_promedio_actual?: number;
            /**
             * @description Cantidad de cabezas iniciales en el lote (opcional)
             * @example 50
             */
            cantidad_actual?: number;
            /**
             * @description Valor por kilo de referencia pactado (opcional)
             * @example 8500
             */
            valor_kilo_referencia?: number;
        };
        ContratoRespuestaDto: {
            /**
             * @description Identificador único UUID del contrato
             * @example d3eedd77-7a0c-4ff6-995d-4aa7ac160b44
             */
            id: string;
            /**
             * @description Identificador UUID del tercero socio en participación
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            tercero_id: string;
            /**
             * @description Identificador UUID de la finca asociada
             * @example b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22
             */
            finca_id: string;
            /**
             * @description Fecha de apertura del contrato en formato ISO 8601 con zona horaria
             * @example 2026-09-21T10:00:00.000Z
             */
            fecha_apertura: string;
            /**
             * @description Porcentaje de participación del comerciante (0 a 100)
             * @example 60
             */
            porcentaje_comerciante: number;
            /**
             * @description Porcentaje de participación del tercero (0 a 100)
             * @example 40
             */
            porcentaje_tercero: number;
            /**
             * @description Estado del contrato
             * @example activo
             * @enum {string}
             */
            estado: "activo" | "cerrado";
            /**
             * @description Fecha de cierre del contrato cuando el inventario llega a cero
             * @example null
             */
            fecha_cierre?: string | null;
            /**
             * @description Raza o cruce del lote de ganado
             * @example Brahman Blanco
             */
            raza?: string | null;
            /**
             * @description Peso promedio actual de los animales en kilogramos
             * @example 350.5
             */
            peso_promedio_actual?: number | null;
            /**
             * @description Cantidad actual de cabezas de ganado en el lote
             * @example 50
             */
            cantidad_actual?: number | null;
            /**
             * @description Valor por kilo de referencia pactado
             * @example 8500
             */
            valor_kilo_referencia?: number | null;
        };
        PaginaContratosDto: {
            /** @description Listado de elementos paginados */
            elementos: components["schemas"]["ContratoRespuestaDto"][];
            /**
             * @description Cantidad total de registros encontrados para el tenant
             * @example 45
             */
            total: number;
            /**
             * @description Límite de registros solicitado o aplicado por página
             * @example 20
             */
            limite: number;
            /**
             * @description Cantidad de registros omitidos desde el inicio
             * @example 0
             */
            offset: number;
        };
        ActualizarContratoDto: {
            /**
             * @description Estado del contrato
             * @example cerrado
             * @enum {string}
             */
            estado?: "activo" | "cerrado";
            /**
             * @description Fecha y hora de cierre del contrato en formato ISO 8601
             * @example 2026-12-31T18:00:00.000Z
             */
            fecha_cierre?: string;
            /**
             * @description Raza o cruce del lote
             * @example Gyr Lechero
             */
            raza?: string;
            /**
             * @description Peso promedio actual de los animales en kg
             * @example 410
             */
            peso_promedio_actual?: number;
            /**
             * @description Cantidad actual de cabezas de ganado
             * @example 35
             */
            cantidad_actual?: number;
            /**
             * @description Valor por kilo de referencia
             * @example 9000
             */
            valor_kilo_referencia?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    UsuariosController_registrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearUsuarioDto"];
            };
        };
        responses: {
            /** @description Comerciante registrado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsuarioRegistradoDto"];
                };
            };
            /** @description Datos de registro inválidos o incompletos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: El email debe ser un correo válido; La contraseña debe tener al menos 8 caracteres",
                     *       "errores": [
                     *         "El email debe ser un correo válido",
                     *         "La contraseña debe tener al menos 8 caracteres"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/usuarios/registro",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description El correo electrónico ya se encuentra registrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "El correo electrónico ya se encuentra registrado",
                     *       "errores": [
                     *         "El correo electrónico ya se encuentra registrado"
                     *       ],
                     *       "codigoEstado": 409,
                     *       "ruta": "/api/v1/usuarios/registro",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorConflictoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/usuarios/registro",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    UsuariosController_acceder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredencialesAccesoDto"];
            };
        };
        responses: {
            /** @description Acceso concedido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccesoRespuestaDto"];
                };
            };
            /** @description Credenciales con formato inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: El email debe ser un correo válido",
                     *       "errores": [
                     *         "El email debe ser un correo válido"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/usuarios/acceso",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description Credenciales de acceso inválidas */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Credenciales de acceso inválidas",
                     *       "errores": [
                     *         "Credenciales de acceso inválidas"
                     *       ],
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/usuarios/acceso",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/usuarios/acceso",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    TercerosController_listar: {
        parameters: {
            query?: {
                /** @description Cantidad máxima de elementos a retornar (entre 1 y 100) */
                limite?: number;
                /** @description Número de elementos a omitir desde el inicio (mínimo 0) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de terceros paginado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaTercerosDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    TercerosController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearTerceroDto"];
            };
        };
        responses: {
            /** @description Tercero creado exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerceroRespuestaDto"];
                };
            };
            /** @description Datos de creación del tercero inválidos o incompletos */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: El nombre es obligatorio; El tipo de tercero debe ser criador, cebador o comisionista",
                     *       "errores": [
                     *         "El nombre es obligatorio",
                     *         "El tipo de tercero debe ser criador, cebador o comisionista"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    TercerosController_buscarPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tercero encontrado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerceroRespuestaDto"];
                };
            };
            /** @description Identificador no es un UUID válido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: Validation failed (uuid is expected)",
                     *       "errores": [
                     *         "Validation failed (uuid is expected)"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/terceros/invalido",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Tercero no encontrado o no pertenece al comerciante */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Tercero no encontrado",
                     *       "errores": [
                     *         "Tercero no encontrado"
                     *       ],
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/terceros/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    TercerosController_eliminar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tercero eliminado correctamente */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identificador no es un UUID válido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: Validation failed (uuid is expected)",
                     *       "errores": [
                     *         "Validation failed (uuid is expected)"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/terceros/invalido",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Tercero no encontrado o no pertenece al comerciante */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Tercero no encontrado",
                     *       "errores": [
                     *         "Tercero no encontrado"
                     *       ],
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/terceros/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description No se puede eliminar el tercero porque tiene contratos activos asociados */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No se puede eliminar el tercero porque tiene contratos activos asociados",
                     *       "errores": [
                     *         "No se puede eliminar el tercero porque tiene contratos activos asociados"
                     *       ],
                     *       "codigoEstado": 409,
                     *       "ruta": "/api/v1/terceros/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorConflictoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    TercerosController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarTerceroDto"];
            };
        };
        responses: {
            /** @description Tercero actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerceroRespuestaDto"];
                };
            };
            /** @description Datos de actualización inválidos o identificador no es UUID válido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: El tipo de tercero debe ser criador, cebador o comisionista",
                     *       "errores": [
                     *         "El tipo de tercero debe ser criador, cebador o comisionista"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/terceros/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Tercero no encontrado o no pertenece al comerciante */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Tercero no encontrado",
                     *       "errores": [
                     *         "Tercero no encontrado"
                     *       ],
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/terceros/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/terceros",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    FincasController_listar: {
        parameters: {
            query?: {
                /** @description Cantidad máxima de elementos a retornar (entre 1 y 100) */
                limite?: number;
                /** @description Número de elementos a omitir desde el inicio (mínimo 0) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de fincas paginado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaFincasDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    FincasController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearFincaDto"];
            };
        };
        responses: {
            /** @description Finca registrada exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FincaRespuestaDto"];
                };
            };
            /** @description Datos de la finca inválidos (e.g. coordenadas fuera de rango) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: La latitud debe estar entre -90 y 90; La longitud debe estar entre -180 y 180",
                     *       "errores": [
                     *         "La latitud debe estar entre -90 y 90",
                     *         "La longitud debe estar entre -180 y 180"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description El tercero asociado no existe o no pertenece al comerciante */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "El tercero especificado no existe o no pertenece al comerciante autenticado",
                     *       "errores": [
                     *         "El tercero especificado no existe o no pertenece al comerciante autenticado"
                     *       ],
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    FincasController_buscarPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finca encontrada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FincaRespuestaDto"];
                };
            };
            /** @description Identificador no es un UUID válido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: Validation failed (uuid is expected)",
                     *       "errores": [
                     *         "Validation failed (uuid is expected)"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/fincas/invalido",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Finca no encontrada o no pertenece a un tercero del comerciante */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Finca no encontrada",
                     *       "errores": [
                     *         "Finca no encontrada"
                     *       ],
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/fincas/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    FincasController_eliminar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Finca eliminada correctamente */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Identificador no es un UUID válido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: Validation failed (uuid is expected)",
                     *       "errores": [
                     *         "Validation failed (uuid is expected)"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/fincas/invalido",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Finca no encontrada o no pertenece a un tercero del comerciante */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Finca no encontrada",
                     *       "errores": [
                     *         "Finca no encontrada"
                     *       ],
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/fincas/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description No se puede eliminar la finca porque tiene contratos activos asociados */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No se puede eliminar la finca porque tiene contratos activos asociados",
                     *       "errores": [
                     *         "No se puede eliminar la finca porque tiene contratos activos asociados"
                     *       ],
                     *       "codigoEstado": 409,
                     *       "ruta": "/api/v1/fincas/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorConflictoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    FincasController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarFincaDto"];
            };
        };
        responses: {
            /** @description Finca actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FincaRespuestaDto"];
                };
            };
            /** @description Datos de actualización inválidos o identificador no es UUID válido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la petición: El área en hectáreas debe ser mayor o igual a 0",
                     *       "errores": [
                     *         "El área en hectáreas debe ser mayor o igual a 0"
                     *       ],
                     *       "codigoEstado": 400,
                     *       "ruta": "/api/v1/fincas/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Finca no encontrada o no pertenece a un tercero del comerciante */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Finca no encontrada",
                     *       "errores": [
                     *         "Finca no encontrada"
                     *       ],
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/fincas/3fa85f64-5717-4562-b3fc-2c963f66afa6",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/fincas",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    ContratosController_listar: {
        parameters: {
            query?: {
                /** @description Cantidad máxima de elementos a retornar (entre 1 y 100) */
                limite?: number;
                /** @description Número de elementos a omitir desde el inicio (mínimo 0) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de contratos obtenido exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaContratosDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    ContratosController_crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearContratoDto"];
            };
        };
        responses: {
            /** @description Contrato aperturado exitosamente */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoRespuestaDto"];
                };
            };
            /** @description Error de validación: campos requeridos ausentes, valores numéricos inválidos o suma de porcentajes distinta de 100 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la solicitud: La suma del porcentaje del comerciante y el porcentaje del tercero debe ser exactamente igual a 100",
                     *       "codigoEstado": 400,
                     *       "errores": [
                     *         "La suma del porcentaje del comerciante y el porcentaje del tercero debe ser exactamente igual a 100"
                     *       ],
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Recurso no encontrado: el tercero no existe en el tenant o la finca no existe/no pertenece al tercero */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "La finca especificada no existe o no pertenece al tercero indicado",
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    ContratosController_buscarPorId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contrato encontrado y retornado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoRespuestaDto"];
                };
            };
            /** @description Identificador UUID con formato inválido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la solicitud",
                     *       "codigoEstado": 400,
                     *       "errores": [
                     *         {
                     *           "campo": "id",
                     *           "mensajes": [
                     *             "Validation failed (uuid v4 is expected)"
                     *           ]
                     *         }
                     *       ],
                     *       "ruta": "/api/v1/contratos/invalido",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Contrato no encontrado o no perteneciente al comerciante */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Contrato no encontrado",
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/contratos/00000000-0000-0000-0000-000000000000",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    ContratosController_actualizar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarContratoDto"];
            };
        };
        responses: {
            /** @description Contrato actualizado exitosamente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContratoRespuestaDto"];
                };
            };
            /** @description Datos inválidos o intento de modificar porcentajes de participación u otros campos inmutables */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error de validación en la solicitud",
                     *       "codigoEstado": 400,
                     *       "errores": [
                     *         {
                     *           "campo": "porcentaje_comerciante",
                     *           "mensajes": [
                     *             "property porcentaje_comerciante should not exist"
                     *           ]
                     *         }
                     *       ],
                     *       "ruta": "/api/v1/contratos/00000000-0000-0000-0000-000000000000",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorValidacionDto"];
                };
            };
            /** @description No autorizado: token JWT ausente o inválido */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "No autorizado: token JWT ausente o inválido",
                     *       "codigoEstado": 401,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoAutorizadoDto"];
                };
            };
            /** @description Contrato no encontrado para actualizar */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Contrato no encontrado",
                     *       "codigoEstado": 404,
                     *       "ruta": "/api/v1/contratos/00000000-0000-0000-0000-000000000000",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorNoEncontradoDto"];
                };
            };
            /** @description Error interno del servidor */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "exito": false,
                     *       "mensaje": "Error interno del servidor",
                     *       "codigoEstado": 500,
                     *       "ruta": "/api/v1/contratos",
                     *       "marcaTiempo": "2026-09-21T16:00:00.000Z"
                     *     }
                     */
                    "application/json": components["schemas"]["RespuestaErrorServidorDto"];
                };
            };
        };
    };
    HealthController_verificar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
